//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 03:23:37 PM CET 
//


package com.realdolmen.fleet.web_service;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for perUsage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="perUsage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="totalkm" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="totalprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="numberplate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="updatedate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "perUsage", propOrder = {
    "totalkm",
    "totalprice",
    "totalfuelinliter",
    "numberplate",
    "updatedate"
})
public class PerUsage {

    protected int totalkm;
    protected double totalprice;
    protected double totalfuelinliter;
    @XmlElement(required = true)
    protected String numberplate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar updatedate;

    /**
     * Gets the value of the totalkm property.
     * 
     */
    public int getTotalkm() {
        return totalkm;
    }

    /**
     * Sets the value of the totalkm property.
     * 
     */
    public void setTotalkm(int value) {
        this.totalkm = value;
    }

    /**
     * Gets the value of the totalprice property.
     * 
     */
    public double getTotalprice() {
        return totalprice;
    }

    /**
     * Sets the value of the totalprice property.
     * 
     */
    public void setTotalprice(double value) {
        this.totalprice = value;
    }

    /**
     * Gets the value of the numberplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberplate() {
        return numberplate;
    }

    /**
     * Sets the value of the numberplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberplate(String value) {
        this.numberplate = value;
    }

    /**
     * Gets the value of the updatedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedate() {
        return updatedate;
    }

    /**
     * Sets the value of the updatedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedate(XMLGregorianCalendar value) {
        this.updatedate = value;
    }

    public double getTotalfuelinliter() {
        return totalfuelinliter;
    }

    public void setTotalfuelinliter(double totalfuelinliter) {
        this.totalfuelinliter = totalfuelinliter;
    }
}
